// <auto-generated />
using System;
using BlazorAssignmentWebApplication.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorAssignmentWebApplication.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210509183524_AddAdult")]
    partial class AddAdult
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BlazorAssignmentWebApplication.Data.Model.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("INTEGER");

                    b.Property<int>("Salary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("BlazorAssignmentWebApplication.Data.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EyeColor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("BlazorAssignmentWebApplication.Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorAssignmentWebApplication.Data.Model.Adult", b =>
                {
                    b.HasBaseType("BlazorAssignmentWebApplication.Data.Model.Person");

                    b.Property<int?>("Job")
                        .HasColumnType("INTEGER");

                    b.HasIndex("Job")
                        .IsUnique();

                    b.ToTable("Adults");
                });

            modelBuilder.Entity("BlazorAssignmentWebApplication.Data.Model.Adult", b =>
                {
                    b.HasOne("BlazorAssignmentWebApplication.Data.Model.Person", null)
                        .WithOne()
                        .HasForeignKey("BlazorAssignmentWebApplication.Data.Model.Adult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAssignmentWebApplication.Data.Model.Job", "JobTitle")
                        .WithOne("JobTitle")
                        .HasForeignKey("BlazorAssignmentWebApplication.Data.Model.Adult", "Job");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("BlazorAssignmentWebApplication.Data.Model.Job", b =>
                {
                    b.Navigation("JobTitle");
                });
#pragma warning restore 612, 618
        }
    }
}
